### ISSUE TITLE
App crash when upgrade v2.6 to 3.0

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-android-sdk#311]
hi All,

I am trying to upgrade android quickblox from v2.6.0 to v3.0. I have a problem: 

18 21:36:52.944 10933 11234 D QBASDK  : 
10-18 21:36:52.954 10933 11234 E AndroidRuntime: FATAL EXCEPTION: JavaBridge
10-18 21:36:52.954 10933 11234 E AndroidRuntime: Process: ch.alarmpb_test, PID: 10933
10-18 21:36:52.954 10933 11234 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.parser.QBJsonParser.parseJsonResponse(QBJsonParser.java:103)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.parser.QBJsonParser.parse(QBJsonParser.java:91)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.Query.parseAccountRequest(Query.java:339)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.Query.access$000(Query.java:36)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.Query$1.completedWithResponse(Query.java:229)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at com.quickblox.core.server.HttpRequestRunnable$1.handleMessage(HttpRequestRunnable.java:43)
10-18 21:36:52.954 10933 11234 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

===============================================================
I used gradle to connect to local dependencies as below:

dependencies {
    compile(name:'quickblox-android-sdk-core-3.0', ext:'aar'){
        transitive=true
    }
    compile(name:'quickblox-android-sdk-chat-3.0', ext:'aar'){
        transitive=true
    }
    compile(name:'quickblox-android-sdk-messages-3.0', ext:'aar'){
        transitive=true
    }
    compile(name:'quickblox-android-sdk-videochat-webrtc-3.0', ext:'aar'){
        transitive=true
    }
    compile(name:'quickblox-android-sdk-extensions-3.0', ext:'aar'){
        transitive=true
    }
    compile(name:'quickblox-android-sdk-customobjects-3.0', ext:'aar'){
        transitive=true
    }
}
repositories{
    flatDir{
        dirs 'libs'
    }
}

could somebody help me on this?

**Comment by tatanka987** [comment]
hello @williamtran1988, please see our documentation how to add the QuickBlox Android SDK to your app.

**Comment by williamtran1988** [comment]
@tatanka987 i could use framework now by using:

repositories {
    maven {
        url "https://github.com/QuickBlox/quickblox-android-sdk-releases/raw/master/"
    }
}
dependencies {
   compile("com.quickblox:quickblox-android-sdk-chat:3.0")
   compile("com.quickblox:quickblox-android-sdk-core:3.0")
   compile("com.quickblox:quickblox-android-sdk-messages:3.0")
   compile("com.quickblox:quickblox-android-sdk-videochat-webrtc:3.0")
   compile("com.quickblox:quickblox-android-sdk-extensions:3.0")
}

It is difficult to config it with local files. Anyway i could work now.

I have another problem while i make a audio call, or accept the call.

1. when i make call, the recipient could not receive call event.
2. I could not accept the call.

Do you know why?

**Comment by tatanka987** [comment]
@williamtran1988 looks like you not set session callback listener for recipient, see our documentation how to prepare your app to calls by [link ](http://quickblox.com/developers/Sample-webrtc-android#Set_QBRTCClient_instance_up)

**Comment by williamtran1988** [comment]
I did, I can call from iphone to my android device, but when i receive a call, i could not join the call.

**Comment by tatanka987** [comment]
please provide us your code where you are doing accept call, additionaly try to reproduce this issue on our sample-videochat-webrtc

**Comment by williamtran1988** [comment]
my accept call process like this:

if (this.currentSession != null) {
			this.currentSession.acceptCall(null);
			Toast.makeText(cordova.getActivity().getApplicationContext(), "accept call", 1000).show();
			//stopRingSound();
		}

I have 2 issues here:
1. Android version upgrade to 3.0 could make a call but receiver not receive.( this receiver can receive from another side).
2. Android version receive a call and accept it. It could not connect.

It's strange. I have not seen any different in configuration here.

**Comment by williamtran1988** [comment]
It looks like i missed room name which is new property in new version right?

**Comment by tatanka987** [comment]
please try to reproduce this issue on our sample

**Comment by williamtran1988** [comment]
your example is working well. as i can see that in your example:

private QBUser createQBUserWithCurrentData(String userName, String chatRoomName) {
        QBUser qbUser = null;
        if (!TextUtils.isEmpty(userName) && !TextUtils.isEmpty(chatRoomName)) {
            StringifyArrayList<String> userTags = new StringifyArrayList<>();
            userTags.add(chatRoomName);

            qbUser = new QBUser();
            qbUser.setFullName(userName);
            qbUser.setLogin(getCurrentDeviceId());
            qbUser.setPassword(Consts.DEFAULT_USER_PASSWORD);
            qbUser.setTags(userTags);
        }

        return qbUser;
    }

we have userTags. is it possible to create user without this field and make a call base on userID only?

**Comment by williamtran1988** [comment]
@tatanka987  does process relate to grant permission to access? What if i manual grant permission?

**Comment by williamtran1988** [comment]
Hi All, can somebody help me to verify my process?  are there something wrong when i could make a call but there are not any recipient receive the call, and when i receive a call, i could not join it:

my process is below:

1. Init framework:
        setting = QBSettings.getInstance();
        setting.init(this.cordova.getActivity().getApplicationContext(), appID, authKey,authSec);
        setting.setAccountKey(accountKey);

        QBRTCConfig.setMaxOpponentsCount(6);
        QBRTCConfig.setDisconnectTime(30);
        QBRTCConfig.setAnswerTimeInterval(60l);
        QBRTCConfig.setStatsReportInterval(60);
        QBRTCConfig.setDebugEnabled(true);

        chatService = QBChatService.getInstance();
        initAudioManager();

2. create app session and login.
      final QBUser user = new QBUser();
		user.setId(params.getInt("ID"));
		user.setPassword(params.getString("password"));
		user.setLogin(params.getString("login"));

		QBAuth.createSession(user).performAsync(new QBEntityCallback<QBSession>() {
            @Override
            public void onSuccess(QBSession session, Bundle bundle) {
               QBChatService.getInstance().login(user)

 3.             ==> initWebRTCClient:

rtcClient = QBRTCClient.getInstance(cordova.getActivity().getApplicationContext());
		chatService.getVideoChatWebRTCSignalingManager()
				.addSignalingManagerListener(new QBVideoChatSignalingManagerListener() {
					@Override
					public void signalingCreated(QBSignaling qbSignaling, boolean createdLocally) {
						if (!createdLocally) {
							rtcClient.addSignaling((QBWebRTCSignaling) qbSignaling);
						}
					}
				});
        rtcClient.setCameraErrorHendler(new VideoCapturerAndroid.CameraEventsHandler() {
            @Override
            public void onCameraError(final String s) {
            }

            @Override
            public void onCameraFreezed(String s) {
            }

            @Override
            public void onCameraOpening(int i) {
            }

            @Override
            public void onFirstFrameAvailable() {
            }

            @Override
            public void onCameraClosed() {
            }
        });
		rtcClient.addSessionCallbacksListener(this);
		rtcClient.prepareToProcessCalls();


3. Make a call 👍 

QBRTCSession newSessionWithOpponents = rtcClient.createNewSessionWithOpponents(opponentsIDs,
				QBRTCTypes.QBConferenceType.QB_CONFERENCE_TYPE_AUDIO);
		if (newSessionWithOpponents != null) {
			this.currentSession = newSessionWithOpponents;
			this.currentSession.addSessionCallbacksListener(this);
			newSessionWithOpponents.startCall(userInfo);

But i never accept call coming or make a call to other user.

Somebody can help me?

**Comment by tatanka987** [comment]
@williamtran1988 please close this issue("App crash when upgrade v2.6 to 3.0") and create new issue with current problem, additionally please attach to new issue full logs form caller's device and from receiver's device

**Comment by williamtran1988** [comment]
yes, ok.
