### ISSUE TITLE
NoClassDefFoundError after upgrading from 2.6 to 3.0 

### ISSUE THREAD

**Issue by Sivious** [QuickBlox/quickblox-android-sdk#294]
I have upgraded Quickblox from 2.6 to 3.0 and followed your guide to adapt the last version. 

A runtime exception is thrown just after setting up QBChatService when executing the following lines: 

`QBChatService.setDebugEnabled(true);`
`QBChatService.setDefaultAutoSendPresenceInterval(60);`

This is the Exception:

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.XXX.jobs, PID: 14055
                  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jivesoftware/smack/tcp/XMPPTCPConnectionConfiguration;
                      at com.quickblox.chat.QBChatService.<clinit>(QBChatService.java:84)
                      at com.XXX.jobs.mvp.presenters.ChatPresenter3.<init>(ChatPresenter3.java:65)
                      at com.XXX.jobs.views.activities.ChatActivity.onCreate(ChatActivity.java:117)
                      at android.app.Activity.performCreate(Activity.java:6251)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration" on path: DexPathList[[dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-universal-image-loader-1.9.5_b16cddd68b820bcad741876abb07d17ac9ecbaf6-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-support-annotations-24.1.0_8459910f84d5a193718d57c400ce4f9583f92f4d-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slf4j-nop-1.7.12_23b5eb3fd9eb679223e436add05f8f851f9663ad-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-slf4j-api-1.7.12_65ad8cea242c564fb4e0ff42f716390cc5e6e7b0-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-retrofit1-okhttp3-client-1.0.2_b8fcfd9bed9c442a7c376fef370e861ebb874917-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-retrofit-1.9.0_f8418d78a89504abf8d862a087210cc60ee64e3d-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-quickblox-android-sdk-messages-3.0_9a9714696f4b60f2d6ee9489701a1c18b16e3601-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-quickblox-android-sdk-core-3.0_c2f25a0ee5ac5d7884088169856a92d676e34a91-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-quickblox-android-sdk-chat-3.0_a468059952589356d85e4e834cb29d97127efe82-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-picasso-2.5.2_053e09cd1d91ae7bd63a5f293692a7bbda761462-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-otto-1.3.8_c98564ccb70f4e55574a2806e622838478c546cf-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-okio-1.6.0_d32fe6568332c1791d491b6b429ef0806006e48f-classes.dex", dex file "/data/data/com.XXX.jobs/files/instant-run/dex/slice-okhttp-3.2.0_3b0041dd4a02445750415809862aabf0b7f695e7-classes.dex", dex f
`

**Comment by vfite** [comment]
Hi there!
Seems like you missed some dependencies from quickblox sdk.
Refer to https://quickblox.com/developers/Android#How_to:_add_SDK_to_IDE_and_connect_to_the_cloud for correct adding sdk via gradle script. 
Note, for including transitive dependencies you should add dependency on particular sdk module -  " compile("com.quickblox:quickblox-android-sdk-chat:2.6.1")" 
not just to resource ("aar" or "jar") -  compile("com.quickblox:quickblox-android-sdk-chat:2.6.1@aar").
Look carefully or provide build.gradle file.
