### ISSUE TITLE
After updating to 2.3 sdk, crash in onLocalVideoTrackReceive

### ISSUE THREAD

**Issue by edovino** [QuickBlox/quickblox-android-sdk#115]
D/Quickblox: onLocalVideoTrackReceive: 
W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/quickblox/videochat/webrtc/view/VideoCallBacks;.canApplyRotation()Z"
W/System.err:     at org.webrtc.VideoRenderer.nativeWrapVideoRenderer(Native Method)
W/System.err:     at org.webrtc.VideoRenderer.<init>(VideoRenderer.java:191)

**Comment by katiatereshchenkova** [comment]
Hi! 
Can you provide us steps to reproduce, device, OS?
Thanks

**Comment by edovino** [comment]
oh, sorry for being unclear. This is on Android 5.1.1, on a Nexus 5

Only thing I changed is swapping the 2.2.6 jars for the 2.3 jars. On 2.2.6 everything works just fine, on 2.3 I suddenly get that NoSuchMethodError
(I only use the sdk-core, sdk-chat and sdk-videochat-webrtc jars)

In fact, I checked the com/quickblox/videochat/webrtc/view/VideoCallBacks class in the SDK, and it doesn't have the method mentioned in the error (canApplyRotation)

**Comment by katiatereshchenkova** [comment]
Please, check, have you updated jniLibs folder, which contains .so files, on the updated folder?

**Comment by edovino** [comment]
no - I wasn't aware that was necessary. They are only in the sample, right?

**Comment by katiatereshchenkova** [comment]
We have updated new SDK version. Please, update your .so files  -  https://github.com/QuickBlox/quickblox-android-sdk/tree/master/sample-videochat-webrtc-new/src/main/jniLibs   and .jar files - https://github.com/QuickBlox/quickblox-android-sdk/tree/master/jars 
And check this issue again
